# Maze Environment

In [1]:
import numpy as np

In [989]:
import math 
import random

In [2]:
from npy_append_array import NpyAppendArray
from collections import deque

In [35]:
env = np.ndarray(shape=(10,10), buffer = np.zeros((10,10)), dtype = int)

In [204]:
def check_path(env, i, j, vis, path, G, x, y):
    vis[i][j] = 1
    if G == 0 and i == x-1 and j == y-1:
        path = 1
        return path
    else:
        if path != 1 and i!=x-1 and env[i+1][j] == 1 and vis[i+1][j] == 0:
            path = check_path(env, i+1, j, vis, path, G, x, y)
        if path != 1 and j != y-1 and env[i][j+1] == 1 and vis[i][j+1] == 0:
            path = check_path(env, i, j+1, vis, path, G, x, y)
        if path != 1 and i!=0 and env[i-1][j] == 1 and vis[i-1][j] == 0:
            path = check_path(env, i-1, j, vis, path, G, x, y)
        if path != 1 and j != 0 and env[i][j-1] == 1 and vis[i][j-1] == 0:
            path = check_path(env, i, j-1, vis, path, G, x, y)
        return path

In [263]:
def create_env(x, y, m):
    n=0
    while (n<m):
        env = np.zeros((x,y), dtype = int)
        vis = np.zeros((x,y), dtype = int)

        for i in range(x):
            for j in range(y):
               env[i][j] = np.random.choice(2, 1, p = [0.28,0.72])
        env[0,0], env[x-1,y-1] = 1, 1

        k = 0
        for i in range(x):
            for j in range(y):
                if env[i][j] == 0:
                    k += 1

        path = check_path(env, 0, 0, vis, 0, 0, x, y)

        if (k/100 < 0.5) and  path == 1:
            n += 1
            with open("test.txt", "ab") as f:
                f.write(b"\n")
                np.savetxt(f, env, fmt = '%1d')
    return env

# Ghost Spawn

In [456]:
spwG = np.zeros((17,17), dtype = int) #where ghost can spawn
path = check_path(env, 0, 0, spwG, 0, 1, 17, 17)
spwG

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0],
       [1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1],
       [1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1],
       [1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1],
       [1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0],
       [1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1],
       [0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [985]:
env_copy  = env.copy()
for i in posG:
    env_copy[i[0]][i[1]] = 0
env_copy, env

(array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1],
        [1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0],
        [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0],
        [0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1],
        [1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1],
        [1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0],
        [1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0],
        [1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0],
        [0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1],
        [0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1],
        [0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0],
        [0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1],
        [1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1],
        [1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1],
        [0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0],
        [0, 0, 0, 1, 1, 

In [982]:
spwG

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0],
       [1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1],
       [1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1],
       [1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1],
       [1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0],
       [1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1],
       [0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [998]:
def ghost_spw(spwG, n, posG, m):
    for i in range(n):
        randRow = 0
        randCol = 0
        while ((randRow == 0 and randCol == 0) or (randRow == m-1 and randCol == m-1) or spwG[randRow][randCol] == 0):
            randRow = random.randint(0,m-1)
            if randRow == 0:
                randCol = random.randint(1, m-1)
            elif randRow == m-1:
                randCol = random.randint(0, m-2)
            else:
                randCol = random.randint(0, m-1)
            print(randRow, randCol)
        posG.append((randRow, randCol))
    return posG

In [1013]:
posG = []
posG = ghost_spw(spwG, 30, posG, 17)

5 16
10 14
14 7
1 8
3 0
7 2
10 12
2 11
11 7
4 6
7 12
0 15
4 1
11 13
4 10
5 15
16 7
5 8
16 10
7 3
1 8
8 12
15 3
14 6
9 15
6 16
5 8
12 9
7 2
2 14
1 6
11 8
16 2
8 16
11 6
15 12
9 15
12 12


In [976]:
randRow = np.random.randint(16, size=1)#[0]
randRow

array([14])

# Ghost Movement

In [761]:
def move_ghosts(posG, env, size):
    for i in range(len(posG)):
        x = posG[i][0]
        y = posG[i][1]
        movedG = False
        while not(movedG):
            move = np.random.randint(4, size = 1)[0]
            if move == 0 and x != 0:
                    movedG = True
                    if env[x-1][y] == 1:
                        x -= 1
                    else:
                        mv_into_wall = np.random.choice(2, 1, p = [0.5, 0.5])
                        if mv_into_wall == 1:
                            x -= 1
            elif move == 1 and y != size-1:
                    movedG = True
                    if env[x][y+1] == 1:
                        y += 1
                    else:
                        mv_into_wall = np.random.choice(2, 1, p = [0.5, 0.5])
                        if mv_into_wall == 1:
                            y += 1
            elif move == 2 and x != size-1:
                    movedG = True
                    if env[x+1][y] == 1:
                        x += 1
                    else:
                        mv_into_wall = np.random.choice(2, 1, p = [0.5, 0.5])
                        if mv_into_wall == 1:
                            x += 1
            elif move == 3 and y != 0:
                    movedG = True
                    if env[x][y-1] == 1:
                        y -= 1
                    else:
                        mv_into_wall = np.random.choice(2, 1, p = [0.5, 0.5])
                        if mv_into_wall == 1:
                            y -= 1
        posG[i] = tuple([x, y])
    return posG            

# Shortest path for Agent 1

In [534]:
def BFS(env, vis, size, start):
    q = [[[start[0], start[1]]]]
    path = list()
    vis[start[0],start[1]] = 1
    #q.append(list([0,0]))
    #print(q)
    while len(q) != 0:
        path = q.pop(0)
        #print("q " , q)
        node = path[-1]
        #print("Path " , path)
        i = node[0]
        j = node[1]
        if i == size-1 and j == size-1:
            return path
        if i!= size-1 and env[i+1][j] == 1 and vis[i+1][j] == 0:
            new_path = list(path)
            #print("new_path1 " , new_path)
            new_path.append([i+1,j])
            #print("new_path2 " , new_path)
            #print("path " , path)
            q.append(new_path)
            #print("q" , q)
            vis[i+1][j] = 1
        if j != size-1 and env[i][j+1] == 1 and vis[i][j+1] == 0:
            new_path = list(path)
            #print("new_path1 " , new_path)
            new_path.append([i,j+1])
            #print("new_path2 " , new_path)
            q.append(new_path)
            vis[i][j+1] = 1
        if i != 0 and env[i-1][j] == 1 and vis[i-1][j] == 0:
            new_path = path
            new_path.append([i-1,j])
            q.append(new_path)
            vis[i-1][j] = 1
        if j != 0 and env[i][j-1] == 1 and vis[i][j-1] == 0:
            new_path = path
            new_path.append([i,j-1])
            q.append(new_path)
            vis[i][j-1] = 1
    

In [541]:
print(BFS(env, vis, 17, [4,7]))

[[4, 7], [5, 7], [6, 7], [7, 7], [8, 7], [8, 8], [9, 8], [10, 8], [11, 8], [12, 8], [13, 8], [14, 8], [15, 8], [16, 8], [16, 9], [16, 10], [16, 11], [16, 12], [16, 13], [16, 14], [16, 15], [16, 16]]


In [698]:
pathF

NameError: name 'pathF' is not defined

In [192]:
q = []
path = []
q.append([0,9])
print(q)
path = list([q.pop(0)])
print(path)
new_path = path
print(new_path)
new_path.append([1,0])
print(new_path)
q.extend(new_path)
q

[[0, 9]]
[[0, 9]]
[[0, 9]]
[[0, 9], [1, 0]]


[[0, 9], [1, 0]]

In [94]:
list([0,1])[1]

1

In [194]:
vis = np.zeros((3,3), dtype = int)
env, vis

(array([[1, 0, 0, 1, 1, 1, 0, 1, 0, 1],
        [1, 1, 1, 1, 1, 0, 1, 0, 1, 1],
        [1, 1, 1, 1, 0, 1, 1, 0, 1, 1],
        [1, 1, 1, 1, 0, 1, 0, 0, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
        [0, 1, 1, 1, 1, 0, 0, 0, 1, 0],
        [1, 1, 1, 0, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 0, 0, 0, 0, 1, 1, 0],
        [1, 0, 1, 1, 0, 1, 1, 0, 1, 1],
        [0, 0, 0, 1, 0, 1, 0, 1, 1, 1]]),
 array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]))

In [273]:
env = create_env(17, 17, 1)
#env = np.array([[1,1,1],[1,1,1],[0,0,1]])

# Agent 1 Game Starts

In [476]:
vis = np.zeros(shape=(17,17), dtype = int)
path = BFS(env, vis, 17, 17)


In [477]:
vis = np.zeros(shape=(17,17), dtype = int)
path = BFS(env, vis, 17)
currA = path[0]
success = 0
j=0
while j<10:
    m=True
    for i in range(len(path)-1):
        currA = path[i+1]
        posG = move_ghosts(posG, env, 17)
        if currA in posG:
            m = False
            break
    if m == True:
        success += 1
    j+=1
success

4

In [478]:
len(path)

33

In [374]:
#currA = path[1]
currA = [5, 12]
currA

[5, 12]

In [434]:
print(posG)

[[6, 6], [9, 2], [8, 4], [11, 10], [14, 4], [16, 15], [7, 13], [6, 4], [7, 11], [12, 3], [10, 9], [3, 2], [10, 13], [15, 5], [10, 16], [11, 9], [13, 13], [8, 15], [8, 4], [3, 12]]


In [376]:
if currA in posG:
    print("Yay")

Yay


# Agent 2 Starts Here

In [542]:
def BFS_w_ghosts(env, posG, size, currA):
    env_copy  = env.copy()
    vis = np.zeros((size, size), dtype = int)
    for i in posG:
        env[i[0]][i[1]] = 1
    path = BFS(env_copy, vis, 17, currA)
    return path

In [1004]:
def move_away(envC, posG, currA):
    min = 100
    for i in posG:
        dis = math.sqrt((currA[1]-i[1])*(currA[1]-i[1])+(currA[0]-i[0])*(currA[0]-i[0]))
        if dis < min:
            min = dis
            minG = i
    if (minG[0] - currA[0]) == 0:
        slope = 1
    else:
        slope = (minG[1] - currA[1])/(minG[0] - currA[0])
    if slope == 1 and minG[1] > 0 and currA[0] < len(envC)-1:
        return (currA[0]+1, currA[1]) 
    elif minG[1] < 0 and currA[0] > 0:
        return (currA[0]-1, currA[1])
    elif slope == 0 and minG[0] > 0 and currA[1] > 0:
        return (currA[0], currA[1]-1)
    elif minG[0] < 0 and currA[1] < 0 and currA[1] < len(envC)-1:
        return (currA[0], currA[1]+1)
    if slope < 1 and slope > -1 and currA[1] > 0 and env[currA[0],currA[1]-1] == 1:
        return (currA[0], currA[1]-1)
    if slope < 1 and slope < -1 and currA[0] > 0 and env[currA[0]-1,currA[1]] == 1:
        return (currA[0]-1, currA[1])
    if slope > 1 and slope < -1 and currA[1] < len(envC)-1 and env[currA[0],currA[1]+1] == 1:
        return (currA[0], currA[1]+1)
    if slope > 1 and slope > -1 and currA[0] < len(envC)-1 and env[currA[0]+1,currA[1]] == 1:
        return (currA[0]+1, currA[1])
    return currA

In [948]:
posG = []
posG = ghost_spw(spwG, 100, posG, 17)

In [628]:
succGA2 = []
for l in range(200):
    success = 0
    print(l)
    for k in range(50):
        currA = [0,0]
        vis = np.zeros(shape=(51, 51), dtype = int)
        j=0
        while j<10:
            posG = []
            posG = ghost_spw(spwL[k][0], l, posG, 51)
            path = BFS_w_ghosts(maze[k][0], posG, 51, currA)
            currA = path[0]
            m=True
            i=0
            while currA != [50, 50]:
                #print(path, i)
                currA = path[i+1]
                if tuple(path[i+1]) in posG:
                    i=-1
                    path = BFS_w_ghosts(maze[k][0], posG, 51, currA)
                if path == None:
                    i=-1
                    currA = move_away(maze[k][0], posG, currA)
                    path = BFS_w_ghosts(maze[k][0], posG, 51, currA)
                #old_posG = posG.copy()
                posG = move_ghosts(posG, maze[k][0], 51)
                if tuple(currA) in posG:
                    m = False
                    break
                i+=1

            if m == True:
                success += 1
            j+=1
    succGA2.append(success/5)

3

In [629]:
old_posG = posG.copy()
print(old_posG)

[[16, 1], [10, 4], [11, 6], [7, 5], [3, 6], [13, 10], [0, 12], [14, 3], [12, 4], [9, 15], [3, 8], [13, 10], [12, 15], [15, 1], [6, 9], [14, 7], [11, 10], [12, 14], [13, 7], [13, 8]]


In [630]:
if posG == old_posG:
    print("yay")

yay


In [634]:
len(env[0])

17

# Agent 3 Begins Here

In [631]:
from queue import PriorityQueue

In [632]:
pq = PriorityQueue

In [643]:
def hscore(cell1, cell2):
    return abs(cell1[0]-cell2[0]) + abs(cell1[1]-cell2[1])

In [926]:
def astar(env, currA, size):
    gscore = {}
    fscore = {}
    childC = None
    for i in range(size):
        for j in range(size):
            gscore[(i,j)] = float('inf')
            fscore[(i,j)] = float('inf')
    #print(gscore, fscore)      
    gscore[(currA[0], currA[1])] = 0
    fscore[(currA[0], currA[1])] = hscore(currA, [size-1, size-1])
    
    pq = PriorityQueue()
    pq.put((hscore(currA, (size-1,size-1)), hscore(currA, (size-1,size-1)), currA))
    pathA = {}
    while not pq.empty():
        currC = tuple(pq.get()[2])
        if currC == (size-1, size-1):
            break
        for i in range(4):
            if i == 0 and currC[1] < size-1 and env[currC[0],currC[1]+1] == 1:
                childC = tuple([currC[0],currC[1]+1])
                tempgscore = gscore[currC]+1
                tempfscore = tempgscore + hscore(childC, (size-1, size-1))
            
                if tempfscore < fscore[childC]:
                    gscore[childC] = tempgscore
                    fscore[childC] = tempfscore
                    pq.put((tempfscore, hscore(childC,(size-1, size-1)), childC))
                    pathA[childC] = currC
            if i == 1 and  currC[0] < size-1 and env[currC[0]+1,currC[1]] == 1:
                childC = (currC[0]+1,currC[1])
                tempgscore = gscore[currC]+1
                tempfscore = tempgscore + hscore(childC, (size-1, size-1))
            
                if tempfscore < fscore[childC]:
                    gscore[childC] = tempgscore
                    fscore[childC] = tempfscore
                    pq.put((tempfscore, hscore(childC,(size-1, size-1)), childC))
                    pathA[childC] = currC
            if i == 2 and currC[1] > 0 and env[currC[0],currC[1]-1] == 1:
                childC = (currC[0],currC[1]-1)
                tempgscore = gscore[currC]+1
                tempfscore = tempgscore + hscore(childC, (size-1, size-1))
            
                if tempfscore < fscore[childC]:
                    gscore[childC] = tempgscore
                    fscore[childC] = tempfscore
                    pq.put((tempfscore, hscore(childC,(size-1, size-1)), childC))
                    pathA[childC] = currC
            if i == 3  and currC[0] > 0 and env[currC[0]-1,currC[1]] == 1:
                childC = (currC[0]-1,currC[1])
                tempgscore = gscore[currC]+1
                tempfscore = tempgscore + hscore(childC, (size-1, size-1))
            
                if tempfscore < fscore[childC]:
                    gscore[childC] = tempgscore
                    fscore[childC] = tempfscore
                    pq.put((tempfscore, hscore(childC,(size-1, size-1)), childC))
                    pathA[childC] = currC
            

    pathF = {}
    #print("currA", currA)
    cell = (size-1, size-1)
    #print("pathA", pathA)
    if pathA.get(cell) == None:
        return None
    while cell != tuple(currA):
        pathF[pathA[cell]] = cell
        cell = pathA[cell]
    #print("pathF", pathF)
    return pathF


In [781]:
def astar_w_ghosts(env, currA, posG):
    env_copy  = env.copy()
    for i in posG:
        env_copy[i[0]][i[1]] = 0
    path = astar(env_copy, currA, len(env))
    return path

In [1017]:
def agent3_game_on(env, posG):
    currC = (0,0)
    size = len(env)
    success = 0
    j=0
    childC = None
    env_copy = env.copy()
    for i in posG:
        env_copy[i[0]][i[1]] = 0
    while j<30:
        m = True
        while currC != (size-1, size-1):
            #print(currC)
            dis = 1000
            minD = 1000
            maxS = 0
            srate = 0
            posG_copy = posG.copy()
            for i in range(5):
                if i == 0 and currC[1] < size-1 and env[currC[0],currC[1]+1] == 1:
                    nextC = (currC[0],currC[1]+1)
                    srate, dis = agent2WAstar(env, nextC, posG_copy)
                if i == 1 and  currC[0] < size-1 and env[currC[0]+1,currC[1]] == 1:
                    nextC = (currC[0]+1,currC[1])
                    srate, dis = agent2WAstar(env, nextC, posG_copy)
                if i == 2 and currC[1] > 0 and env[currC[0],currC[1]-1] == 1:
                    nextC = (currC[0],currC[1]-1)
                    srate, dis = agent2WAstar(env, nextC, posG_copy)
                if i == 3  and currC[0] > 0 and env[currC[0]-1,currC[1]] == 1:
                    nextC = (currC[0]-1,currC[1])
                    srate, dis = agent2WAstar(env, nextC, posG_copy)
                if i == 4:
                    nextC = (currC)
                    srate, dis = agent2WAstar(env, nextC, posG_copy)
                #print(i, srate, max)
                if srate > maxS:
                    maxS = srate
                    childC = nextC
                if dis < minD and dis != 0 and srate == maxS:
                    minD = dis
                    childC = nextC
            if childC != None:
                currC = childC
            elif srate == 0:
                currC = move_away(env_copy, posG, currC)
                
            posG = move_ghosts(posG, env, 17)
            
            if currC in posG:
                m = False
                break
        if m==True:
            success += 1 
        print(success)
        j += 1
    return success

In [1020]:
def agent2WAstar(env, currA, posG):
    path = {}
    size = len(env)
    if currA == (size-1, size-1):
        return 1,0.1
    path = astar_w_ghosts(env, currA, posG)
    if path == None:
        return -1, 0
    #print("agent2WAstar", path)
    env_copy = env.copy()
    for i in posG:
        env_copy[i[0]][i[1]] = 0
    success = 0
    dis = 0
    j=0
    while j<10:
        m=True
        while currA != (size-1, size-1):
            if path != None:
                currA = path.get(currA)
            else:
                dis = 0
                m = False
                break
            posG = move_ghosts(posG, env, size)
            if currA in posG:
                dis = 0
                m = False
                break
            if path.get(currA) in posG:
                path = astar_w_ghosts(env, currA, posG)
            if path == None:
                currA = move_away(env_copy, posG, currA)
                path = astar_w_ghosts(env, currA, posG)
            #old_posG = posG.copy()
            dis += 1
        if m == True:
            success += 1
        j+=1
    return success/10, dis/10

In [816]:
agent2WAstar(env, (0,0), posG)

{(15, 16): (16, 16), (14, 16): (15, 16), (13, 16): (14, 16), (12, 16): (13, 16), (11, 16): (12, 16), (11, 15): (11, 16), (11, 14): (11, 15), (10, 14): (11, 14), (10, 13): (10, 14), (10, 12): (10, 13), (9, 12): (10, 12), (8, 12): (9, 12), (8, 11): (8, 12), (7, 11): (8, 11), (7, 10): (7, 11), (6, 10): (7, 10), (6, 9): (6, 10), (6, 8): (6, 9), (6, 7): (6, 8), (6, 6): (6, 7), (5, 6): (6, 6), (5, 5): (5, 6), (5, 4): (5, 5), (5, 3): (5, 4), (4, 3): (5, 3), (4, 2): (4, 3), (4, 1): (4, 2), (4, 0): (4, 1), (3, 0): (4, 0), (2, 0): (3, 0), (1, 0): (2, 0), (0, 0): (1, 0)}
{(15, 16): (16, 16), (14, 16): (15, 16), (13, 16): (14, 16), (12, 16): (13, 16), (11, 16): (12, 16), (11, 15): (11, 16), (11, 14): (11, 15), (10, 14): (11, 14), (10, 13): (10, 14), (10, 12): (10, 13), (9, 12): (10, 12), (8, 12): (9, 12), (8, 11): (8, 12), (7, 11): (8, 11), (7, 10): (7, 11), (6, 10): (7, 10), (6, 9): (6, 10), (6, 8): (6, 9), (6, 7): (6, 8), (6, 6): (6, 7), (5, 6): (6, 6), (5, 5): (5, 6), (5, 4): (5, 5), (5, 3): (5

In [1002]:
env_copy  = env.copy()
for i in posG:
    env_copy[i[0]][i[1]] = 0
env_copy, env

(array([[1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1],
        [0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0],
        [1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1],
        [0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1],
        [0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0],
        [0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0],
        [1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0],
        [1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0],
        [1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1],
        [0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1],
        [0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1],
        [0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1],
        [1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1],
        [0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1],
        [0, 1, 1, 1, 1, 

In [1021]:
agent3_game_on(env, posG)

0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16


16

In [887]:
print(path, np.asarray(env_copy, dtype = int))

None [[1 1 1 1 1 1 1 1 1 0 1 1 1 0 0 1 0]
 [1 0 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1]
 [1 1 0 1 1 1 0 1 0 1 1 0 1 1 0 1 0]
 [1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1]
 [1 1 1 1 1 1 1 0 1 0 1 1 0 0 1 0 1]
 [0 1 0 1 1 0 1 1 1 1 1 0 1 1 1 0 1]
 [1 1 0 1 1 1 1 0 1 1 1 1 0 1 1 0 0]
 [1 1 1 1 1 1 1 1 1 1 1 0 1 0 1 1 0]
 [1 1 1 1 1 1 1 0 1 1 0 1 1 0 0 0 1]
 [0 1 1 1 1 1 1 1 1 1 0 1 1 1 1 0 1]
 [0 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1]
 [0 1 0 1 0 0 0 1 0 0 1 0 1 1 0 1 1]
 [0 1 1 1 1 1 1 0 1 1 1 0 1 1 0 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [0 0 1 0 1 0 0 1 0 1 1 1 1 1 1 1 1]
 [0 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1]]


In [896]:
env1 = np.array([[1,1,1],[0,1,0],[0,1,1]])

In [928]:
env

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0],
       [1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1],
       [1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1],
       [1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1],
       [1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0],
       [1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1],
       [0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [996]:
posG, len(posG)

([(10, 2),
  (5, 3),
  (10, 14),
  (8, 4),
  (10, 0),
  (1, 1),
  (3, 4),
  (14, 5),
  (11, 1),
  (0, 12),
  (6, 4),
  (3, 2),
  (14, 2),
  (3, 13),
  (13, 12),
  (11, 2),
  (12, 12),
  (9, 2),
  (10, 12),
  (6, 13),
  (10, 6),
  (15, 10),
  (16, 13),
  (13, 8),
  (15, 12),
  (15, 3),
  (15, 5),
  (0, 6),
  (4, 11),
  (1, 3),
  (9, 15),
  (16, 3),
  (8, 9),
  (13, 6),
  (16, 11),
  (4, 15),
  (7, 7),
  (1, 6),
  (12, 9),
  (12, 15),
  (12, 1),
  (7, 3),
  (0, 8),
  (13, 8),
  (12, 6),
  (13, 1),
  (13, 6),
  (6, 1),
  (3, 12),
  (14, 11),
  (6, 14),
  (1, 12),
  (16, 11),
  (5, 5),
  (2, 7),
  (10, 14),
  (6, 10),
  (2, 12),
  (15, 5),
  (5, 5),
  (8, 6),
  (9, 1),
  (1, 9),
  (5, 1),
  (9, 12),
  (3, 13),
  (16, 10),
  (16, 13),
  (1, 10),
  (7, 4),
  (16, 1),
  (0, 12),
  (2, 4),
  (16, 9),
  (14, 4),
  (1, 9),
  (11, 6),
  (6, 12),
  (3, 0),
  (5, 9),
  (7, 11),
  (4, 13),
  (12, 14),
  (2, 4),
  (0, 1),
  (2, 2),
  (4, 1),
  (15, 12),
  (6, 6),
  (5, 5),
  (3, 1),
  (6, 6),
  (4, 0

In [895]:
print(path)

None
